---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minimom
data:
  projectName: minimom
  #baseUrl: {{ OM_HOST }}
  baseUrl: http://minimom:8080
---
apiVersion: v1
kind: Secret
metadata:
  name: minimom
type: Opaque
stringData:
  user: {{ OM_USER }}
  publicApiKey: {{ OM_API_KEY }}
